### ISSUE TITLE
Bluetooth does not work

### ISSUE THREAD

**Issue by darvd29** [TomaszBochenek/asus-t100ha-linux#1]
I did everything as in readme.md, it fixed the WiFi but Bluetooth doesn't detect any devices. I can attach logs if you tell me which and how to do so :)

**Comment by Dark4Codrutz** [comment]
It depends on the Bluetooth chipset that you have.
If you have the integrated broadcom bt+WiFi (brcm4324b4) as in my T100TA, then brcmfmac modulr would take care of BT as well, but you have to copy into /lib/firmware/brcm/ the BCM**.hcd file from a working Windows driver files (you could also find one online) as they are not provided by default.

**Comment by Dark4Codrutz** [comment]
Mine is BCM43142, and you can find the file here: https://github.com/winterheart/broadcom-bt-firmware

To find out if it is your case run:
dmesg | grep brcm*
And look for a line like "brcmfmac: could not find BCMxxx.hcd file"
If no such error message you might have another bt chip, check with 'lspci' , or your kernel is not patched for broadcom UART (eg. older kernel)

**Comment by darvd29** [comment]
Thank you, I have found the file I needed and it works now :)
